"""empty message

Revision ID: 83e96d583fef
Revises: fbeef5715e75
Create Date: 2024-05-01 17:56:26.478779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83e96d583fef'
down_revision = 'fbeef5715e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('amount_unit',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('amount_unit',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
