"""initial migration

Revision ID: fbeef5715e75
Revises: 
Create Date: 2024-04-24 14:30:17.326759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbeef5715e75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.alter_column('time',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('time_unit',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Enum('MINUTES', 'HOURS', name='timeunit'),
               existing_nullable=False)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('time_unit',
               existing_type=sa.Enum('MINUTES', 'HOURS', name='timeunit'),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
